
#ifndef CLENSHAWCURTISEXPERIMENT_PRIVATE_HXX
#define CLENSHAWCURTISEXPERIMENT_PRIVATE_HXX

/* From http://gcc.gnu.org/wiki/Visibility */
/* Generic helper definitions for shared library support */
#if defined _WIN32 || defined __CYGWIN__
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_IMPORT __declspec(dllimport)
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_EXPORT __declspec(dllexport)
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_LOCAL
#else
#if __GNUC__ >= 4
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_IMPORT __attribute__ ((visibility ("default")))
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_EXPORT __attribute__ ((visibility ("default")))
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_LOCAL  __attribute__ ((visibility ("hidden")))
#else
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_IMPORT
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_EXPORT
#define CLENSHAWCURTISEXPERIMENT_HELPER_DLL_LOCAL
#endif
#endif

/* Now we use the generic helper definitions above to define CLENSHAWCURTISEXPERIMENT_API and CLENSHAWCURTISEXPERIMENT_LOCAL.
 * CLENSHAWCURTISEXPERIMENT_API is used for the public API symbols. It either DLL imports or DLL exports (or does nothing for static build)
 * CLENSHAWCURTISEXPERIMENT_LOCAL is used for non-api symbols. */

#ifndef CLENSHAWCURTISEXPERIMENT_STATIC /* defined if OT is compiled as a DLL */
#ifdef CLENSHAWCURTISEXPERIMENT_DLL_EXPORTS /* defined if we are building the OT DLL (instead of using it) */
#define CLENSHAWCURTISEXPERIMENT_API CLENSHAWCURTISEXPERIMENT_HELPER_DLL_EXPORT
#else
#define CLENSHAWCURTISEXPERIMENT_API CLENSHAWCURTISEXPERIMENT_HELPER_DLL_IMPORT
#endif /* CLENSHAWCURTISEXPERIMENT_DLL_EXPORTS */
#define CLENSHAWCURTISEXPERIMENT_LOCAL CLENSHAWCURTISEXPERIMENT_HELPER_DLL_LOCAL
#else /* CLENSHAWCURTISEXPERIMENT_STATIC is defined: this means OT is a static lib. */
#define CLENSHAWCURTISEXPERIMENT_API
#define CLENSHAWCURTISEXPERIMENT_LOCAL
#endif /* !CLENSHAWCURTISEXPERIMENT_STATIC */


#endif // CLENSHAWCURTISEXPERIMENT_PRIVATE_HXX

